### ISSUE TITLE
Lost sofia

### ISSUE THREAD

**Issue by markggallagher** [signalwire/freeswitch#662]
I successfully compiled and installed freeswitch, and configured several phones to work with the default config. Phones registered fine, and completed internal calls, tested IVR, call-park, music-on-hold, etc. All good internally. 

I have an account from a SIP provider that I've used successfully before. 

I tried to setup the external SIP profile, but could not get my new XML file to take, and I tried to modify the default External file, but no change. I kept trying to modify external.xml. At some point, I must have fuzzed something, because now; while freeswitch starts, phones do not register, and if I run "sofia status" I get "-ERR sofia status Command not found!"

I've tried retracing my steps and thought I had undone my edits, but still no luck. 

Any help/suggestions is appreciated.

**Comment by andywolk** [comment]
What freeswitch version?

**Comment by markggallagher** [comment]
Version 1.10.2

**Comment by andywolk** [comment]
Your mod_sofia is not loaded due to missing external ip because of STUN failure.
That's fixed in 1.10.3 by
```
[mod_sofia] Add abort-on-empty-external-ip global param disabled by default.
```

**Comment by markggallagher** [comment]
I added the parameter mentioned to the sofia conf file and it did work; however, I continued to try to get my external profile to work (by creating a file called iptel.org.xml in the external SIP profiles directory) and again Sofia is not loading. The disabled abort param is still there. Tried undoing my changes buy it still doesn't load. What am I doing wrong here?
